projectName: wqp-external
dockerImageName: kartoza/geoserver
memory: 2048
applicationName: wqp-geoserver
rulePriority: 93
containerPort: 8080
healthCheck: /geoserver/web/
contextPath: /geoserver/*
gitRepoUrl: https://github.com/NWQMC/wqp-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
mounts:
  - name: 'geoserverMount',
    source: '/efs',
    destination: '/wqp-geoserver-data'
